name: mga_env
channels:
  - pytorch
  - conda-forge
  - defaults
  - pkgs/main
dependencies:
  - spacy-model-en_core_web_trf
  - pillow=9.2.0
  - pip=22.2.2
  - python=3.9.13
  - pip:
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - albumentations==1.1.0
    - arc==1.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - bert-score==0.3.13
    - blinker==1.7.0
    - cachetools==5.3.3
    - cloudpathlib==0.16.0
    - cycler==0.12.1
    - datasets==2.3.2
    - dill==0.3.5.1
    - evaluate==0.2.2
    - flask==3.0.2
    - fonttools==4.49.0
    - frozenlist==1.4.1
    - google-auth==2.28.2
    - google-auth-oauthlib==0.4.6cico
    - imageio==2.34.0
    - imagesize==1.3.0
    - itsdangerous==2.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - matplotlib==3.5.2
    - multidict==6.0.5
    - multiprocess==0.70.13
    - networkx==3.2.1
    - nltk==3.7
    - numpy==1.22.3
    - oauthlib==3.2.2
    - opencv-python==4.5.2.54
    - opencv-python-headless==4.9.0.80
    - pandas==1.4.2
    - patsy==0.5.6
    - protobuf==3.20.1
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.5
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - qudida==0.0.4
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.1.2
    - rsa==4.9
    - scikit-image==0.22.0
    - scikit-learn==1.1.2
    - scipy==1.11.4
    - setuptools==69.2.0
    - spacy==3.5.4
    - spacy-transformers==1.3.4
    - statsmodels==0.13.2
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - thinc==8.1.12
    - threadpoolctl==3.3.0
    - tifffile==2024.2.12
    - tokenizers==0.12.1
    - torch==1.12.0
    - torch-tb-profiler==0.4.3
    - torchinfo==1.7.0
    - torchmetrics==0.9.3
    - torchvision==0.13.0
    - tqdm==4.64.0
    - transformers==4.19.2
    - typing-extensions==4.10.0
    - weasel==0.3.4
    - yarl==1.9.4
